import fs from 'node:fs';
import path from 'node:path';

interface ImageImport {
  node: any;
  variableName: string;
  originalUrl: string;
}

function isLocalImage(url: string) {
  return !(
    url.startsWith('http://') ||
    url.startsWith('https://') ||
    url.startsWith('//') ||
    url.startsWith('data:') ||
    url.startsWith('/')
  );
}

/**
 * Reads the image imports generated by Rspress' built-in remarkImage plugin.
 * User remark plugins run after that built-in plugin in Rspress 2, so the
 * original Markdown `image` nodes no longer exist when this plugin executes.
 */
function getImageImport(node: any): ImageImport | undefined {
  if (node?.type !== 'mdxjsEsm') {
    return undefined;
  }

  const declaration = node.data?.estree?.body?.[0];
  const specifier = declaration?.specifiers?.[0];
  const originalUrl = declaration?.source?.value;
  const variableName = specifier?.local?.name;

  if (
    declaration?.type !== 'ImportDeclaration' ||
    specifier?.type !== 'ImportDefaultSpecifier' ||
    typeof originalUrl !== 'string' ||
    typeof variableName !== 'string' ||
    !variableName.startsWith('image') ||
    !isLocalImage(originalUrl)
  ) {
    return undefined;
  }

  return {
    node,
    variableName,
    originalUrl,
  };
}

/**
 * Resolves legacy image conventions without rewriting Markdown:
 * `a.png`, `image/a.png`, `images/a.png`, and `assets/a.png`.
 */
function resolveImageUrl(
  markdownDirectory: string,
  originalUrl: string,
) {
  const match = originalUrl.match(/^([^?#]*)([?#].*)?$/);

  if (!match) {
    return undefined;
  }

  const imagePath = match[1];
  const suffix = match[2] || '';
  const directPath = path.resolve(
    markdownDirectory,
    imagePath,
  );

  if (fs.existsSync(directPath)) {
    const relativeUrl =
      imagePath.startsWith('./') ||
      imagePath.startsWith('../')
        ? imagePath
        : `./${imagePath}`;

    return `${relativeUrl}${suffix}`;
  }

  for (const directory of ['image', 'images', 'assets']) {
    const candidateUrl = `${directory}/${imagePath}`;
    const candidatePath = path.resolve(
      markdownDirectory,
      candidateUrl,
    );

    if (fs.existsSync(candidatePath)) {
      return `./${candidateUrl}${suffix}`;
    }
  }

  return undefined;
}

function updateImportSource(
  imageImport: ImageImport,
  resolvedUrl: string,
) {
  const declaration =
    imageImport.node.data.estree.body[0];

  declaration.source.value = resolvedUrl;
  declaration.source.raw = JSON.stringify(resolvedUrl);
  imageImport.node.value =
    `import ${imageImport.variableName} from ${JSON.stringify(
      resolvedUrl,
    )}`;
}

function replaceMissingImages(
  node: any,
  missingImages: Map<string, string>,
) {
  if (!node) {
    return;
  }

  if (
    (node.type === 'mdxJsxFlowElement' ||
      node.type === 'mdxJsxTextElement') &&
    node.name === 'img'
  ) {
    const sourceAttribute = node.attributes?.find(
      (attribute: any) => attribute?.name === 'src',
    );
    const variableName = sourceAttribute?.value?.value;
    const originalUrl = missingImages.get(variableName);

    if (originalUrl) {
      /*
       * The asset is absent from the repository. Replacing the generated MDX
       * element with text prevents an unresolved import while keeping a visible
       * marker in the rendered article.
       */
      node.type = 'text';
      node.value = `[图片不存在：${originalUrl}]`;
      delete node.name;
      delete node.attributes;
      delete node.children;
      return;
    }
  }

  if (Array.isArray(node.children)) {
    for (const child of node.children) {
      replaceMissingImages(child, missingImages);
    }
  }
}

export function fixImagePath() {
  return function transformer(tree: any, file: any) {
    const filePath = file.path || file.history?.[0];

    if (!filePath || !Array.isArray(tree.children)) {
      return;
    }

    const markdownDirectory = path.dirname(filePath);
    const missingImages = new Map<string, string>();

    /*
     * Rewrite generated imports when a legacy asset directory contains the
     * image. Imports for genuinely missing files are removed before Rspack
     * resolves modules.
     */
    tree.children = tree.children.filter((node: any) => {
      const imageImport = getImageImport(node);

      if (!imageImport) {
        return true;
      }

      const resolvedUrl = resolveImageUrl(
        markdownDirectory,
        imageImport.originalUrl,
      );

      if (resolvedUrl) {
        updateImportSource(imageImport, resolvedUrl);
        return true;
      }

      missingImages.set(
        imageImport.variableName,
        imageImport.originalUrl,
      );
      return false;
    });

    if (missingImages.size === 0) {
      return;
    }

    replaceMissingImages(tree, missingImages);

    console.warn(
      `[fix-image-path] ${path.relative(
        process.cwd(),
        filePath,
      )}: ${missingImages.size} 张图片不存在`,
    );
  };
}
